name: Update Resi Graphs

on:
  workflow_dispatch:

  schedule:
    - cron: "0 10 * * *"

jobs:
  analyze:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        region: [eu, na]

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Clone private DB repo
        env:
          PRIVATE_REPO_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
        run: |
          git clone https://x-access-token:${PRIVATE_REPO_TOKEN}@github.com/hocus-p0cus/mplus-data-fetcher.git db_repo

      - name: Copy DB files to workspace
        run: cp db_repo/*.db .

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run analysis for region ${{ matrix.region }}
        run: |
          python main.py \
            --region ${{ matrix.region }} \
            --season tww-season3 \
            --resi-key-level 20

      - name: Upload analysis results
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.region }}
          path: |
            *_timestamps.json
            *_down_edges.json
            *_non_resil_edges.json
